name: shuchu
description: "A minimalist pomodoro timer."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: IosevkaNerdFont
      fonts:
        - asset: fonts/IosevkaNerdFont-Thin.ttf
          style: normal
